"""
cargar_linaje.py
Carga el mapa de linaje de los 53 campos del reporte 0430 a MongoDB Atlas.
Solo necesitas correrlo una vez (o cuando actualices el linaje).

Uso:
  python cargar_linaje.py
"""

import os
from pymongo import MongoClient
from dotenv import load_dotenv

load_dotenv()

mongo = MongoClient(os.getenv("MONGO_URI"))
db = mongo[os.getenv("DB_NAME")]

LINAJE = [
    {
        "reporte": "0430", "numero": 1, "clave": "PERIODO",
        "nombre": "Período",
        "linaje": "Campo default — período de reporte en formato AAAAMM",
        "origen": "Default", "hoja_excel": "—", "columna_excel": "—", "tipo": "Default",
        "obligatorio": "Sí", "formato": "Numérico, 6 dígitos AAAAMM", "catalogo": "—",
        "condiciones": "Siempre obligatorio. Formato AAAAMM donde AA=año y MM=mes del reporte.",
        "relacionados": ["REPORTE", "CLAVE_INSTITUCION"],
    },
    {
        "reporte": "0430", "numero": 2, "clave": "CLAVE_INSTITUCION",
        "nombre": "Clave de la Institución",
        "linaje": "Campo default — clave de la institución asignada por CNBV",
        "origen": "Default", "hoja_excel": "—", "columna_excel": "—", "tipo": "Default",
        "obligatorio": "Sí", "formato": "Numérico, 5 dígitos", "catalogo": "Catálogo de Instituciones CNBV",
        "condiciones": "Siempre obligatorio. Asignada por la CNBV a cada institución.",
        "relacionados": ["PERIODO", "REPORTE"],
    },
    {
        "reporte": "0430", "numero": 3, "clave": "REPORTE",
        "nombre": "Reporte",
        "linaje": "Campo default — valor fijo '0430'",
        "origen": "Default", "hoja_excel": "—", "columna_excel": "—", "tipo": "Default",
        "obligatorio": "Sí", "formato": "Texto, 4 caracteres", "catalogo": "—",
        "condiciones": "Siempre '0430' para altas de créditos comerciales.",
        "relacionados": ["PERIODO", "CLAVE_INSTITUCION"],
    },
    {
        "reporte": "0430", "numero": 4, "clave": "ID_ACREDITADO",
        "nombre": "Identificador del Acreditado",
        "linaje": "Insumo PERSONA — columna Id_Persona",
        "origen": "Insumo", "hoja_excel": "PERSONA", "columna_excel": "ID_PERSONA", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Texto, máximo 22 caracteres", "catalogo": "—",
        "condiciones": "Debe ser único por acreditado. Si el mismo acreditado tiene múltiples créditos, el ID debe ser el mismo en todos los registros.",
        "relacionados": ["NOMBRE", "RFC", "CURP", "ID_LINEACREDITO"],
    },
    {
        "reporte": "0430", "numero": 5, "clave": "NOMBRE",
        "nombre": "Nombre del Acreditado",
        "linaje": "Insumo PERSONA — columna NOMBRE_CNBV",
        "origen": "Insumo", "hoja_excel": "PERSONA", "columna_excel": "NOMBRE_CNBV", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Texto, máximo 250 caracteres", "catalogo": "—",
        "condiciones": "Para personas morales no debe incluir tipo de sociedad (S.A., S.R.L., etc). Para fideicomisos debe coincidir con la Base de Fideicomisos CNBV.",
        "relacionados": ["ID_ACREDITADO", "RFC", "CURP"],
    },
    {
        "reporte": "0430", "numero": 6, "clave": "RFC",
        "nombre": "RFC del Acreditado",
        "linaje": "Insumo PERSONA — columna RFC, con ajuste según tipo de cartera",
        "origen": "Insumo", "hoja_excel": "PERSONA", "columna_excel": "RFC", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Texto, 13 caracteres", "catalogo": "—",
        "condiciones": "Cuando Tipo de Cartera es 131, 132, 210, 220, 230, 240, 250, 260, 310, 510, 520, 530, 570, 580 debe iniciar con guion bajo (_). Para personas físicas 13 caracteres, para morales 12 caracteres más un espacio.",
        "relacionados": ["CURP", "NOMBRE", "ID_ACREDITADO", "TPO_CARTERA"],
    },
    {
        "reporte": "0430", "numero": 7, "clave": "CURP",
        "nombre": "CURP del Acreditado",
        "linaje": "Insumo PERSONA — columna CURP",
        "origen": "Insumo", "hoja_excel": "PERSONA", "columna_excel": "CURP", "tipo": "Manual",
        "obligatorio": "Condicional", "formato": "Texto, 18 caracteres", "catalogo": "—",
        "condiciones": "Solo aplica para personas físicas. Para personas morales se envía vacío.",
        "relacionados": ["RFC", "NOMBRE", "ID_ACREDITADO"],
    },
    {
        "reporte": "0430", "numero": 8, "clave": "LOCALIDAD",
        "nombre": "Localidad del Domicilio del Acreditado",
        "linaje": "Insumo PERSONA — columna LOCALIDAD",
        "origen": "Insumo", "hoja_excel": "PERSONA", "columna_excel": "LOCALIDAD", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Texto, 8 caracteres", "catalogo": "Catálogo de Localidades INEGI/CNBV",
        "condiciones": "Código de 8 caracteres del catálogo INEGI: SS-MMM-LLLL donde SS=estado, MMM=municipio, LLLL=localidad.",
        "relacionados": ["MUNICIPIO", "ESTADO"],
    },
    {
        "reporte": "0430", "numero": 9, "clave": "MUNICIPIO",
        "nombre": "Municipio del Domicilio del Acreditado",
        "linaje": "Campo calculado — se deriva de la LOCALIDAD del acreditado usando catálogo CNBV",
        "origen": "Calculado", "hoja_excel": "—", "columna_excel": "—", "tipo": "Calculado",
        "obligatorio": "Sí", "formato": "Texto, 3 caracteres (posiciones 3-5 de LOCALIDAD)", "catalogo": "Catálogo de Localidades INEGI/CNBV",
        "condiciones": "Se extrae automáticamente de la LOCALIDAD. Posiciones 3 a 5 del código de 8 caracteres.",
        "relacionados": ["LOCALIDAD", "ESTADO"],
    },
    {
        "reporte": "0430", "numero": 10, "clave": "ESTADO",
        "nombre": "Estado del Domicilio del Acreditado",
        "linaje": "Campo calculado — se deriva de la LOCALIDAD del acreditado usando catálogo CNBV",
        "origen": "Calculado", "hoja_excel": "—", "columna_excel": "—", "tipo": "Calculado",
        "obligatorio": "Sí", "formato": "Texto, 2 caracteres (posiciones 1-2 de LOCALIDAD)", "catalogo": "Catálogo de Localidades INEGI/CNBV",
        "condiciones": "Se extrae automáticamente de la LOCALIDAD. Primeras 2 posiciones del código.",
        "relacionados": ["LOCALIDAD", "MUNICIPIO"],
    },
    {
        "reporte": "0430", "numero": 11, "clave": "NACIONALIDAD",
        "nombre": "Nacionalidad del Acreditado",
        "linaje": "Insumo PERSONA — columna NACIONALIDAD",
        "origen": "Insumo", "hoja_excel": "PERSONA", "columna_excel": "NACIONALIDAD", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Texto, 3 caracteres", "catalogo": "Catálogo de Países CNBV",
        "condiciones": "Código ISO 3166-1 alpha-3. Para mexicanos: MEX.",
        "relacionados": ["RFC", "ID_ACREDITADO"],
    },
    {
        "reporte": "0430", "numero": 12, "clave": "ACT_ECONOMICA",
        "nombre": "Actividad Económica del Acreditado",
        "linaje": "Insumo PERSONA — columna Actividad_Economica",
        "origen": "Insumo", "hoja_excel": "PERSONA", "columna_excel": "ACTIVIDAD_ECONOMICA", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Numérico, 4 dígitos", "catalogo": "Catálogo de Actividades Económicas CNBV",
        "condiciones": "Actividad económica del acreditado, no necesariamente la del destino del crédito.",
        "relacionados": ["ACT_ECONOMICA_DESTINO", "DESTINO"],
    },
    {
        "reporte": "0430", "numero": 13, "clave": "GPO_RIESGO",
        "nombre": "Grupo de Riesgo Común",
        "linaje": "Insumo PERSONA — columna Grupo_Riesgo_Comun, con ajuste",
        "origen": "Insumo", "hoja_excel": "PERSONA", "columna_excel": "GRUPO_RIESGO_COMUN", "tipo": "Manual",
        "obligatorio": "Condicional", "formato": "Texto, máximo 22 caracteres", "catalogo": "—",
        "condiciones": "Solo aplica cuando el acreditado pertenece a un grupo de riesgo común. Se deja vacío si no aplica.",
        "relacionados": ["ID_ACREDITADO", "ACRED_RELACIONADO"],
    },
    {
        "reporte": "0430", "numero": 14, "clave": "ACRED_RELACIONADO",
        "nombre": "Acreditado Relacionado",
        "linaje": "Insumo PERSONA — columna Persona_Relacionada",
        "origen": "Insumo", "hoja_excel": "PERSONA", "columna_excel": "PERSONA_RELACIONADA", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Numérico, 1 dígito (0=No, 1=Sí)", "catalogo": "—",
        "condiciones": "Indica si el acreditado es persona relacionada con la institución según el artículo 73 de la Ley de Instituciones de Crédito.",
        "relacionados": ["GPO_RIESGO", "ID_ACREDITADO"],
    },
    {
        "reporte": "0430", "numero": 15, "clave": "TPO_CARTERA",
        "nombre": "Tipo de Cartera",
        "linaje": "Insumo PERSONA — columna Tipo_Cartera",
        "origen": "Insumo", "hoja_excel": "PERSONA", "columna_excel": "TIPO_CARTERA", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Numérico, 3 dígitos", "catalogo": "Catálogo de Tipos de Cartera CNBV",
        "condiciones": "Determina el Tipo de Anexo y afecta varias validaciones como el formato del RFC.",
        "relacionados": ["TPO_ANEXO", "RFC", "DESTINO", "PRC_PART_FEDERALES"],
    },
    {
        "reporte": "0430", "numero": 16, "clave": "TPO_ANEXO",
        "nombre": "Tipo de Anexo",
        "linaje": "Campo calculado — se determina con base en el tipo de cartera",
        "origen": "Calculado", "hoja_excel": "—", "columna_excel": "—", "tipo": "Calculado",
        "obligatorio": "Sí", "formato": "Numérico, 1 dígito", "catalogo": "—",
        "condiciones": "Se deriva del Tipo de Cartera. Determina qué Anexo del CUB aplica al registro.",
        "relacionados": ["TPO_CARTERA"],
    },
    {
        "reporte": "0430", "numero": 17, "clave": "NUM_SIC",
        "nombre": "Número de Consulta a la SIC",
        "linaje": "Insumo PERSONA — columna Folio_Consulta_Buro",
        "origen": "Insumo", "hoja_excel": "PERSONA", "columna_excel": "FOLIO_CONSULTA_BURO", "tipo": "Manual",
        "obligatorio": "Condicional", "formato": "Numérico, máximo 22 dígitos", "catalogo": "—",
        "condiciones": "Obligatorio cuando se realizó consulta a Sociedad de Información Crediticia (Buró de Crédito).",
        "relacionados": ["ID_ACREDITADO", "RFC"],
    },
    {
        "reporte": "0430", "numero": 18, "clave": "LEI",
        "nombre": "Clave LEI",
        "linaje": "Insumo PERSONA — columna LEI",
        "origen": "Insumo", "hoja_excel": "PERSONA", "columna_excel": "LEI", "tipo": "Manual",
        "obligatorio": "Condicional", "formato": "Texto, 20 caracteres", "catalogo": "—",
        "condiciones": "Solo aplica para personas morales con operaciones internacionales que cuenten con clave LEI (Legal Entity Identifier).",
        "relacionados": ["ID_ACREDITADO", "NOMBRE"],
    },
    {
        "reporte": "0430", "numero": 19, "clave": "ID_LINEACREDITO",
        "nombre": "Identificador del Crédito (Institución)",
        "linaje": "Insumo ajustado — identificador de la línea de crédito asignado por la institución",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "ID_LINEACREDITO", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Texto, máximo 22 caracteres", "catalogo": "—",
        "condiciones": "Identificador propio de la institución para la línea. Diferente al ID_CREDITO_CNBV que sigue la metodología CNBV.",
        "relacionados": ["ID_CREDITO_CNBV", "ID_ACREDITADO"],
    },
    {
        "reporte": "0430", "numero": 20, "clave": "ID_CREDITO_CNBV",
        "nombre": "Identificador del Crédito (Metodología CNBV)",
        "linaje": "Campo calculado — se construye de acuerdo con el Anexo 3 de las Ayudas de la CNBV",
        "origen": "Calculado", "hoja_excel": "—", "columna_excel": "—", "tipo": "Calculado",
        "obligatorio": "Sí", "formato": "Texto, 29 caracteres", "catalogo": "Anexo 3 Metodología CNBV",
        "condiciones": "Fórmula: [Tipo Crédito 1 dígito] + [Institución 6 dígitos] + [Fecha AAAAMM] + [RFC 13 caracteres] + [Consecutivo 3 dígitos]. Único e irrepetible.",
        "relacionados": ["ID_LINEACREDITO", "RFC", "CLAVE_INSTITUCION", "FECHA_OTORGAMIENTO"],
    },
    {
        "reporte": "0430", "numero": 21, "clave": "ID_LINEA_GRUPAL_CNBV",
        "nombre": "Identificador Crédito Línea Grupal (CNBV)",
        "linaje": "Campo calculado — se construye con base en CLIENTE_GRUPAL y el Anexo 4",
        "origen": "Calculado", "hoja_excel": "—", "columna_excel": "—", "tipo": "Calculado",
        "obligatorio": "Condicional", "formato": "Texto, 29 caracteres", "catalogo": "Anexo 4 Metodología CNBV",
        "condiciones": "Solo aplica cuando el crédito pertenece a una línea grupal. Sigue metodología del Anexo 4.",
        "relacionados": ["ID_CREDITO_CNBV", "ID_LINEACREDITO"],
    },
    {
        "reporte": "0430", "numero": 22, "clave": "DESTINO",
        "nombre": "Destino del Crédito",
        "linaje": "Insumo LINEA_CREDITO — columna Destinocreditocc",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "DESTINOCREDITOCC", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Numérico, 3 dígitos", "catalogo": "Catálogo de Destinos de Crédito CNBV",
        "condiciones": "Debe ser congruente con el Tipo de Cartera. Algunos destinos solo aplican para ciertos tipos de cartera.",
        "relacionados": ["TPO_CARTERA", "ACT_ECONOMICA_DESTINO", "LOCALIDAD_DESTINO", "PRC_PART_FEDERALES"],
    },
    {
        "reporte": "0430", "numero": 23, "clave": "MONTO_LINEA_VALORIZADO",
        "nombre": "Monto Línea Autorizado Valorizado en Pesos",
        "linaje": "Campo calculado — se obtiene valorizando el monto a pesos según tipo de moneda",
        "origen": "Calculado", "hoja_excel": "—", "columna_excel": "—", "tipo": "Calculado",
        "obligatorio": "Sí", "formato": "Numérico, hasta 22 dígitos con 2 decimales", "catalogo": "Criterio Contable A-2 Banxico",
        "condiciones": "Si la moneda es MXN se reporta igual al monto original. Para moneda extranjera o UDIS se convierte usando el tipo de cambio del Criterio Contable A-2.",
        "relacionados": ["MONTO_LINEA_MONEDA_ORIGEN", "MONEDA"],
    },
    {
        "reporte": "0430", "numero": 24, "clave": "MONTO_LINEA_MONEDA_ORIGEN",
        "nombre": "Monto Línea Autorizado en Moneda Origen",
        "linaje": "Insumo LINEA_CREDITO — columna Montolineaaut (en moneda de origen)",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "MONTOLINEAAUT", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Numérico, hasta 22 dígitos con 2 decimales", "catalogo": "—",
        "condiciones": "Se reporta en la moneda original del crédito antes de cualquier conversión.",
        "relacionados": ["MONTO_LINEA_VALORIZADO", "MONEDA"],
    },
    {
        "reporte": "0430", "numero": 25, "clave": "FECHA_OTORGAMIENTO",
        "nombre": "Fecha de Otorgamiento",
        "linaje": "Insumo LINEA_CREDITO — columna Fecha_Otorg_Linea",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "FECHA_OTORG_LINEA", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Numérico, 6 dígitos AAAAMM", "catalogo": "—",
        "condiciones": "No puede ser posterior al período del reporte. Forma parte del cálculo del ID_CREDITO_CNBV.",
        "relacionados": ["ID_CREDITO_CNBV", "FECHA_VENCIMIENTO", "TPO_ALTA"],
    },
    {
        "reporte": "0430", "numero": 26, "clave": "FECHA_VENCIMIENTO",
        "nombre": "Fecha de Vencimiento",
        "linaje": "Insumo LINEA_CREDITO — columna Fecha_Venc_Linea, ajustado: solo AAAAMM",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "FECHA_VENC_LINEA", "tipo": "Manual",
        "obligatorio": "Condicional", "formato": "Numérico, 6 dígitos AAAAMM", "catalogo": "—",
        "condiciones": "Obligatorio para créditos con plazo definido. Para créditos revolventes sin fecha fija puede omitirse.",
        "relacionados": ["FECHA_OTORGAMIENTO", "FECHA_MAXIMA_DISP"],
    },
    {
        "reporte": "0430", "numero": 27, "clave": "FECHA_MAXIMA_DISP",
        "nombre": "Fecha Máxima para Disponer",
        "linaje": "Insumo LINEA_CREDITO — columna Fecha_Max_Disp, ajustado: solo AAAAMM",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "FECHA_MAX_DISP", "tipo": "Manual",
        "obligatorio": "Condicional", "formato": "Numérico, 6 dígitos AAAAMM", "catalogo": "—",
        "condiciones": "Obligatorio cuando existe un plazo límite para hacer disposiciones. No puede ser posterior a la FECHA_VENCIMIENTO.",
        "relacionados": ["FECHA_VENCIMIENTO", "FORMA_DISP"],
    },
    {
        "reporte": "0430", "numero": 28, "clave": "FORMA_DISP",
        "nombre": "Forma de Disposición",
        "linaje": "Insumo LINEA_CREDITO — columna Disposicion_Credito",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "DISPOSICION_CREDITO", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Numérico, 1 dígito", "catalogo": "Catálogo de Formas de Disposición CNBV",
        "condiciones": "Determina si el crédito es de disposición única o múltiple.",
        "relacionados": ["REVOCABLE", "FECHA_MAXIMA_DISP"],
    },
    {
        "reporte": "0430", "numero": 29, "clave": "REVOCABLE",
        "nombre": "Línea Revocable o Irrevocable",
        "linaje": "Insumo LINEA_CREDITO — columna Revocable_Irrevocable",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "REVOCABLE_IRREVOCABLE", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Numérico, 1 dígito (1=Revocable, 2=Irrevocable)", "catalogo": "—",
        "condiciones": "Indica si la institución puede cancelar la línea unilateralmente (revocable) o no (irrevocable).",
        "relacionados": ["FORMA_DISP", "MONTO_LINEA_VALORIZADO"],
    },
    {
        "reporte": "0430", "numero": 30, "clave": "PRELACION",
        "nombre": "Prelación de Pago",
        "linaje": "Insumo LINEA_CREDITO — columna Prelacion",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "PRELACION", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Numérico, 1 dígito (1=Preferente, 2=Subordinado)", "catalogo": "—",
        "condiciones": "Indica la prelación en caso de liquidación. Afecta el cálculo de reservas.",
        "relacionados": ["TPO_CARTERA"],
    },
    {
        "reporte": "0430", "numero": 31, "clave": "PRC_PART_FEDERALES",
        "nombre": "Porcentaje de Participaciones Federales",
        "linaje": "Insumo LINEA_CREDITO — columna Porcpartfederal",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "PORCPARTFEDERAL", "tipo": "Manual",
        "obligatorio": "Condicional", "formato": "Numérico, hasta 6 decimales (porcentaje)", "catalogo": "—",
        "condiciones": "Solo aplica cuando el DESTINO del crédito es a estados o municipios con participaciones federales como fuente de pago. Debe estar entre 0 y 100.",
        "relacionados": ["DESTINO", "TPO_CARTERA"],
    },
    {
        "reporte": "0430", "numero": 32, "clave": "CVE_INST_OTORGANTE",
        "nombre": "Clave de la Institución Otorgante",
        "linaje": "Insumo LINEA_CREDITO — columna Instituto_Fondea",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "INSTITUTO_FONDEA", "tipo": "Manual",
        "obligatorio": "Condicional", "formato": "Numérico, 5 dígitos", "catalogo": "Catálogo de Instituciones CNBV",
        "condiciones": "Solo aplica cuando los recursos provienen de otra institución o agencia del exterior. Si la institución otorga con recursos propios se deja vacío.",
        "relacionados": ["CLAVE_INSTITUCION", "MONTO_LINEA_VALORIZADO"],
    },
    {
        "reporte": "0430", "numero": 33, "clave": "TPO_ALTA",
        "nombre": "Tipo de Alta del Crédito",
        "linaje": "Insumo LINEA_CREDITO — columna Tipo_Alta",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "TIPO_ALTA", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Numérico, 1 dígito (1=Alta nueva, 2=Reapertura)", "catalogo": "—",
        "condiciones": "1=Crédito nuevo que nunca se ha reportado. 2=Crédito que se reportó en el pasado y se reactiva. Solo se reporta en el 0430 (altas).",
        "relacionados": ["FECHA_OTORGAMIENTO", "ID_CREDITO_CNBV"],
    },
    {
        "reporte": "0430", "numero": 34, "clave": "MONEDA",
        "nombre": "Moneda de la Línea de Crédito",
        "linaje": "Insumo LINEA_CREDITO — columna Moneda_Linea",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "MONEDA_LINEA", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Numérico, 2 dígitos", "catalogo": "Catálogo de Monedas CNBV",
        "condiciones": "Determina si el monto debe valorizarse a pesos (campo 23). Código según catálogo CNBV.",
        "relacionados": ["MONTO_LINEA_VALORIZADO", "MONTO_LINEA_MONEDA_ORIGEN"],
    },
    {
        "reporte": "0430", "numero": 35, "clave": "TPO_TASA",
        "nombre": "Tipo de Tasa de Interés",
        "linaje": "Insumo LINEA_CREDITO — columna Tipo_Tasa",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "TIPO_TASA", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Numérico, 2 dígitos", "catalogo": "Catálogo de Tipos de Tasa CNBV",
        "condiciones": "Si la tasa es fija, los campos DIF_TASA y OPER_DIF_TASA no aplican.",
        "relacionados": ["DIF_TASA", "OPER_DIF_TASA", "FREC_REVISION_TASA", "CAT"],
    },
    {
        "reporte": "0430", "numero": 36, "clave": "DIF_TASA",
        "nombre": "Diferencial sobre Tasa de Referencia",
        "linaje": "Insumo LINEA_CREDITO — columna Difer_Tasa",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "DIFER_TASA", "tipo": "Manual",
        "obligatorio": "Condicional", "formato": "Numérico, hasta 6 decimales", "catalogo": "—",
        "condiciones": "Solo aplica cuando el Tipo de Tasa es variable. Indica el margen sobre la tasa de referencia.",
        "relacionados": ["TPO_TASA", "OPER_DIF_TASA"],
    },
    {
        "reporte": "0430", "numero": 37, "clave": "OPER_DIF_TASA",
        "nombre": "Operación del Diferencial",
        "linaje": "Insumo LINEA_CREDITO — columna Oper_Dif_Tasa",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "OPER_DIF_TASA", "tipo": "Manual",
        "obligatorio": "Condicional", "formato": "Numérico, 1 dígito (1=Aditiva, 2=Factor)", "catalogo": "—",
        "condiciones": "Solo aplica cuando hay diferencial de tasa. Indica si el diferencial es aditivo (tasa + margen) o factor (tasa × margen).",
        "relacionados": ["DIF_TASA", "TPO_TASA"],
    },
    {
        "reporte": "0430", "numero": 38, "clave": "FREC_REVISION_TASA",
        "nombre": "Frecuencia de Revisión de Tasa",
        "linaje": "Insumo LINEA_CREDITO — columna FrecuenciaRevisionTasa",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "FRECUENCIAREVISIONTASA", "tipo": "Manual",
        "obligatorio": "Condicional", "formato": "Numérico, 2 dígitos", "catalogo": "Catálogo de Frecuencias CNBV",
        "condiciones": "Solo aplica para tasas variables. Indica cada cuánto se revisa la tasa de referencia.",
        "relacionados": ["TPO_TASA", "DIF_TASA"],
    },
    {
        "reporte": "0430", "numero": 39, "clave": "PERIODICIDAD_CAPITAL",
        "nombre": "Periodicidad de Pagos de Capital",
        "linaje": "Insumo LINEA_CREDITO — columna PeriodicidadCapital",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "PERIODICIDADCAPITAL", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Numérico, 2 dígitos", "catalogo": "Catálogo de Periodicidades CNBV",
        "condiciones": "Frecuencia con la que el acreditado debe pagar capital.",
        "relacionados": ["PERIODICIDAD_INTERES", "MESES_GRACIA_CAPITAL"],
    },
    {
        "reporte": "0430", "numero": 40, "clave": "PERIODICIDAD_INTERES",
        "nombre": "Periodicidad de Pagos de Intereses",
        "linaje": "Insumo LINEA_CREDITO — columna PeriodicidadInteres",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "PERIODICIDADINTERES", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Numérico, 2 dígitos", "catalogo": "Catálogo de Periodicidades CNBV",
        "condiciones": "Frecuencia con la que el acreditado debe pagar intereses.",
        "relacionados": ["PERIODICIDAD_CAPITAL", "MESES_GRACIA_INTERES"],
    },
    {
        "reporte": "0430", "numero": 41, "clave": "MESES_GRACIA_CAPITAL",
        "nombre": "Meses de Gracia para Capital",
        "linaje": "Insumo LINEA_CREDITO — columna MesesGraciaCap",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "MESESGRACIACAP", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Numérico, hasta 3 dígitos", "catalogo": "—",
        "condiciones": "Número de meses al inicio del crédito en que no se paga capital. Si no hay gracia se reporta 0.",
        "relacionados": ["PERIODICIDAD_CAPITAL", "MESES_GRACIA_INTERES"],
    },
    {
        "reporte": "0430", "numero": 42, "clave": "MESES_GRACIA_INTERES",
        "nombre": "Meses de Gracia para Intereses",
        "linaje": "Insumo LINEA_CREDITO — columna MesesGraciaIntereses",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "MESESGRACIAINTERESES", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Numérico, hasta 3 dígitos", "catalogo": "—",
        "condiciones": "Número de meses al inicio del crédito en que no se pagan intereses. Si no hay gracia se reporta 0.",
        "relacionados": ["PERIODICIDAD_INTERES", "MESES_GRACIA_CAPITAL"],
    },
    {
        "reporte": "0430", "numero": 43, "clave": "COMISION_APERTURA_TASA",
        "nombre": "Comisión de Apertura (Tasa)",
        "linaje": "Insumo LINEA_CREDITO — columna Comisionapert_Tasa",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "COMISIONAPERT_TASA", "tipo": "Manual",
        "obligatorio": "Condicional", "formato": "Numérico, hasta 6 decimales (porcentaje)", "catalogo": "—",
        "condiciones": "Solo si hay comisión de apertura expresada en tasa. Se deja vacío si la comisión es en monto o no existe. Entra en el cálculo del CAT.",
        "relacionados": ["COMISION_APERTURA_MONTO", "CAT"],
    },
    {
        "reporte": "0430", "numero": 44, "clave": "COMISION_APERTURA_MONTO",
        "nombre": "Comisión de Apertura (Monto)",
        "linaje": "Insumo LINEA_CREDITO — columna Comisionapert_Monto",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "COMISIONAPERT_MONTO", "tipo": "Manual",
        "obligatorio": "Condicional", "formato": "Numérico, hasta 22 dígitos con 2 decimales", "catalogo": "—",
        "condiciones": "Solo si hay comisión de apertura expresada en monto en pesos. Se deja vacío si la comisión es en tasa o no existe. Entra en el cálculo del CAT.",
        "relacionados": ["COMISION_APERTURA_TASA", "CAT"],
    },
    {
        "reporte": "0430", "numero": 45, "clave": "COMISION_DISPOSICION_TASA",
        "nombre": "Comisión por Disposición (Tasa)",
        "linaje": "Insumo LINEA_CREDITO — columna Comisiondisp_Tasa",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "COMISIONDISP_TASA", "tipo": "Manual",
        "obligatorio": "Condicional", "formato": "Numérico, hasta 6 decimales (porcentaje)", "catalogo": "—",
        "condiciones": "Solo si hay comisión por disposición expresada en tasa. Entra en el cálculo del CAT.",
        "relacionados": ["COMISION_DISPOSICION_MONTO", "CAT"],
    },
    {
        "reporte": "0430", "numero": 46, "clave": "COMISION_DISPOSICION_MONTO",
        "nombre": "Comisión por Disposición (Monto)",
        "linaje": "Insumo LINEA_CREDITO — columna Comisiondisp_Monto",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "COMISIONDISP_MONTO", "tipo": "Manual",
        "obligatorio": "Condicional", "formato": "Numérico, hasta 22 dígitos con 2 decimales", "catalogo": "—",
        "condiciones": "Solo si hay comisión por disposición expresada en monto. Entra en el cálculo del CAT.",
        "relacionados": ["COMISION_DISPOSICION_TASA", "CAT"],
    },
    {
        "reporte": "0430", "numero": 47, "clave": "CAT",
        "nombre": "Costo Anual Total (CAT)",
        "linaje": "Insumo LINEA_CREDITO — columna CAT",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "CAT", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Numérico, hasta 6 decimales (porcentaje base 100)", "catalogo": "Circular 21/2009 Banxico",
        "condiciones": "Calculado por la institución siguiendo la Circular 21/2009 de Banxico. Incluye tasa, comisiones y seguros obligatorios. Se reporta en porcentaje base 100.",
        "relacionados": ["TPO_TASA", "COMISION_APERTURA_TASA", "COMISION_APERTURA_MONTO", "MONTO_PRIMAS_ANUALES"],
    },
    {
        "reporte": "0430", "numero": 48, "clave": "MONTO_LINEA_SIN_ACCESORIOS",
        "nombre": "Monto de la Línea sin Accesorios",
        "linaje": "Insumo LINEA_CREDITO — columna MontoLineaSinA",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "MONTOLINEASINA", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Numérico, hasta 22 dígitos con 2 decimales", "catalogo": "—",
        "condiciones": "Monto del crédito sin incluir accesorios financieros como seguros o comisiones capitalizadas.",
        "relacionados": ["MONTO_LINEA_VALORIZADO", "MONTO_PRIMAS_ANUALES"],
    },
    {
        "reporte": "0430", "numero": 49, "clave": "MONTO_PRIMAS_ANUALES",
        "nombre": "Monto de Primas Anuales de Seguros",
        "linaje": "Insumo LINEA_CREDITO — columna MontoPrimasAnuales",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "MONTOPRIMASANUALES", "tipo": "Manual",
        "obligatorio": "Condicional", "formato": "Numérico, hasta 22 dígitos con 2 decimales", "catalogo": "—",
        "condiciones": "Solo aplica cuando el crédito tiene seguros obligatorios. Suma de todas las primas anuales de seguros requeridos.",
        "relacionados": ["CAT", "MONTO_LINEA_SIN_ACCESORIOS"],
    },
    {
        "reporte": "0430", "numero": 50, "clave": "LOCALIDAD_DESTINO",
        "nombre": "Localidad de Destino del Crédito",
        "linaje": "Insumo LINEA_CREDITO — columna LocalidadDestino",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "LOCALIDADDESTINO", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Texto, 8 caracteres", "catalogo": "Catálogo de Localidades INEGI/CNBV",
        "condiciones": "Localidad donde se destinará el crédito. Puede ser diferente a la localidad del acreditado.",
        "relacionados": ["MUNICIPIO_DESTINO", "ESTADO_DESTINO", "DESTINO"],
    },
    {
        "reporte": "0430", "numero": 51, "clave": "MUNICIPIO_DESTINO",
        "nombre": "Municipio de Destino del Crédito",
        "linaje": "Campo calculado — se deriva de la LOCALIDAD_DESTINO usando catálogo CNBV",
        "origen": "Calculado", "hoja_excel": "—", "columna_excel": "—", "tipo": "Calculado",
        "obligatorio": "Sí", "formato": "Texto, 3 caracteres (posiciones 3-5 de LOCALIDAD_DESTINO)", "catalogo": "Catálogo de Localidades INEGI/CNBV",
        "condiciones": "Se extrae automáticamente de LOCALIDAD_DESTINO. Posiciones 3 a 5 del código de 8 caracteres.",
        "relacionados": ["LOCALIDAD_DESTINO", "ESTADO_DESTINO"],
    },
    {
        "reporte": "0430", "numero": 52, "clave": "ESTADO_DESTINO",
        "nombre": "Estado de Destino del Crédito",
        "linaje": "Campo calculado — se deriva de la LOCALIDAD_DESTINO usando catálogo CNBV",
        "origen": "Calculado", "hoja_excel": "—", "columna_excel": "—", "tipo": "Calculado",
        "obligatorio": "Sí", "formato": "Texto, 2 caracteres (posiciones 1-2 de LOCALIDAD_DESTINO)", "catalogo": "Catálogo de Localidades INEGI/CNBV",
        "condiciones": "Se extrae automáticamente de LOCALIDAD_DESTINO. Primeras 2 posiciones del código.",
        "relacionados": ["LOCALIDAD_DESTINO", "MUNICIPIO_DESTINO"],
    },
    {
        "reporte": "0430", "numero": 53, "clave": "ACT_ECONOMICA_DESTINO",
        "nombre": "Actividad Económica de Destino",
        "linaje": "Insumo LINEA_CREDITO — columna ActividadEconomicaDestino",
        "origen": "Insumo", "hoja_excel": "LINEA_CREDITO", "columna_excel": "ACTIVIDADECONOMICADESTINO", "tipo": "Manual",
        "obligatorio": "Sí", "formato": "Numérico, 4 dígitos", "catalogo": "Catálogo de Actividades Económicas CNBV",
        "condiciones": "Actividad económica a la que se destinará el crédito. Puede ser diferente a la del acreditado (campo 12).",
        "relacionados": ["ACT_ECONOMICA", "DESTINO", "LOCALIDAD_DESTINO"],
    },
]


def cargar():
    col = db["linaje_0430"]

    # Borrar existentes del reporte 0430
    col.delete_many({"reporte": "0430"})
    print("🗑️  Registros anteriores eliminados")

    col.insert_many(LINAJE)
    print(f"✅ {len(LINAJE)} campos cargados a la colección 'linaje_0430'")

    # Crear índice por reporte + número
    col.create_index([("reporte", 1), ("numero", 1)], unique=True)
    col.create_index([("reporte", 1), ("clave", 1)])
    print("📇 Índices creados")


if __name__ == "__main__":
    print("🏦 Cargando linaje del reporte 0430 a MongoDB Atlas...")
    print("=" * 50)
    cargar()
    print("=" * 50)
    print("✨ Listo — ya puedes eliminar el diccionario de linaje_0430.py")