# linaje_0430.py
# Mapa de linaje de los 53 campos del reporte 0430
# Extraído de la pestaña "SALIDA ESPERADA 430" del caso de pruebas
# y cotejado con analisis_0430.json

LINAJE_0430 = {
    "REPORTE":                    "Campo default — valor fijo '0430'",
    "PERIODO":                    "Campo default — período de reporte en formato AAAAMM",
    "CLAVE_INSTITUCION":          "Campo default — clave de la institución asignada por CNBV",
    "ID_ACREDITADO":              "Insumo PERSONA — columna Id_Persona",
    "NOMBRE":                     "Insumo PERSONA — columna NOMBRE_CNBV",
    "RFC":                        "Insumo PERSONA — columna RFC, con ajuste según tipo de cartera",
    "CURP":                       "Insumo PERSONA — columna CURP",
    "LOCALIDAD":                  "Insumo PERSONA — columna LOCALIDAD",
    "MUNICIPIO":                  "Campo calculado — se deriva de la LOCALIDAD del acreditado usando catálogo CNBV",
    "ESTADO":                     "Campo calculado — se deriva de la LOCALIDAD del acreditado usando catálogo CNBV",
    "NACIONALIDAD":               "Insumo PERSONA — columna NACIONALIDAD",
    "ACT_ECONOMICA":              "Insumo PERSONA — columna Actividad_Economica",
    "GPO_RIESGO":                 "Insumo PERSONA — columna Grupo_Riesgo_Comun, con ajuste",
    "ACRED_RELACIONADO":          "Insumo PERSONA — columna Persona_Relacionada",
    "TPO_CARTERA":                "Insumo PERSONA — columna Tipo_Cartera",
    "TPO_ANEXO":                  "Campo calculado — se determina con base en el tipo de cartera y el Anexo correspondiente",
    "NUM_SIC":                    "Insumo PERSONA — columna Folio_Consulta_Buro",
    "LEI":                        "Insumo PERSONA — columna LEI",
    "ID_LINEACREDITO":            "Insumo ajustado — identificador de la línea de crédito asignado por la institución",
    "ID_CREDITO_CNBV":            "Campo calculado — se construye de acuerdo con el Anexo 3 de las Ayudas de la CNBV",
    "ID_LINEA_GRUPAL_CNBV":       "Campo calculado — se construye con base en el insumo CLIENTE_GRUPAL y el Anexo 4 de las Ayudas",
    "DESTINO":                    "Insumo LINEA_CREDITO — columna Destinocreditocc",
    "MONTO_LINEA_VALORIZADO":     "Campo calculado — se obtiene valorizando el monto de la línea a pesos según el tipo de moneda",
    "MONTO_LINEA_MONEDA_ORIGEN":  "Insumo LINEA_CREDITO — columna Montolineaaut (en moneda de origen)",
    "FECHA_OTORGAMIENTO":         "Insumo LINEA_CREDITO — columna Fecha_Otorg_Linea",
    "FECHA_VENCIMIENTO":          "Insumo LINEA_CREDITO — columna Fecha_Venc_Linea, ajustado: se toma solo AAAAMM",
    "FECHA_MAXIMA_DISP":          "Insumo LINEA_CREDITO — columna Fecha_Max_Disp, ajustado: se toma solo AAAAMM",
    "FORMA_DISP":                 "Insumo LINEA_CREDITO — columna Disposicion_Credito",
    "REVOCABLE":                  "Insumo LINEA_CREDITO — columna Revocable_Irrevocable",
    "PRELACION":                  "Insumo LINEA_CREDITO — columna Prelacion",
    "PRC_PART_FEDERALES":         "Insumo LINEA_CREDITO — columna Porcpartfederal",
    "CVE_INST_OTORGANTE":         "Insumo LINEA_CREDITO — columna Instituto_Fondea",
    "TPO_ALTA":                   "Insumo LINEA_CREDITO — columna Tipo_Alta",
    "MONEDA":                     "Insumo LINEA_CREDITO — columna Moneda_Linea",
    "TPO_TASA":                   "Insumo LINEA_CREDITO — columna Tipo_Tasa",
    "DIF_TASA":                   "Insumo LINEA_CREDITO — columna Difer_Tasa",
    "OPER_DIF_TASA":              "Insumo LINEA_CREDITO — columna Oper_Dif_Tasa",
    "FREC_REVISION_TASA":         "Insumo LINEA_CREDITO — columna FrecuenciaRevisionTasa",
    "PERIODICIDAD_CAPITAL":       "Insumo LINEA_CREDITO — columna PeriodicidadCapital",
    "PERIODICIDAD_INTERES":       "Insumo LINEA_CREDITO — columna PeriodicidadInteres",
    "MESES_GRACIA_CAPITAL":       "Insumo LINEA_CREDITO — columna MesesGraciaCap",
    "MESES_GRACIA_INTERES":       "Insumo LINEA_CREDITO — columna MesesGraciaIntereses",
    "COMISION_APERTURA_TASA":     "Insumo LINEA_CREDITO — columna Comisionapert_Tasa",
    "COMISION_APERTURA_MONTO":    "Insumo LINEA_CREDITO — columna Comisionapert_Monto",
    "COMISION_DISPOSICION_TASA":  "Insumo LINEA_CREDITO — columna Comisiondisp_Tasa",
    "COMISION_DISPOSICION_MONTO": "Insumo LINEA_CREDITO — columna Comisiondisp_Monto",
    "CAT":                        "Insumo LINEA_CREDITO — columna CAT",
    "MONTO_LINEA_SIN_ACCESORIOS": "Insumo LINEA_CREDITO — columna MontoLineaSinA",
    "MONTO_PRIMAS_ANUALES":       "Insumo LINEA_CREDITO — columna MontoPrimasAnuales",
    "LOCALIDAD_DESTINO":          "Insumo LINEA_CREDITO — columna LocalidadDestino",
    "MUNICIPIO_DESTINO":          "Campo calculado — se deriva de la LOCALIDAD_DESTINO usando catálogo CNBV",
    "ESTADO_DESTINO":             "Campo calculado — se deriva de la LOCALIDAD_DESTINO usando catálogo CNBV",
    "ACT_ECONOMICA_DESTINO":      "Insumo LINEA_CREDITO — columna ActividadEconomicaDestino",
}

# Alias — nombres cortos, largos (CUB), variantes y números de campo
ALIAS_0430 = {
    # Nombres cortos / abreviados
    "reporte":                          "REPORTE",
    "periodo":                          "PERIODO",
    "clave institucion":                "CLAVE_INSTITUCION",
    "id acreditado":                    "ID_ACREDITADO",
    "nombre":                           "NOMBRE",
    "nombre cnbv":                      "NOMBRE",
    "rfc":                              "RFC",
    "curp":                             "CURP",
    "localidad":                        "LOCALIDAD",
    "municipio":                        "MUNICIPIO",
    "estado":                           "ESTADO",
    "nacionalidad":                     "NACIONALIDAD",
    "actividad economica":              "ACT_ECONOMICA",
    "act economica":                    "ACT_ECONOMICA",
    "grupo de riesgo":                  "GPO_RIESGO",
    "gpo riesgo":                       "GPO_RIESGO",
    "acreditado relacionado":           "ACRED_RELACIONADO",
    "tipo de cartera":                  "TPO_CARTERA",
    "tpo cartera":                      "TPO_CARTERA",
    "tipo de anexo":                    "TPO_ANEXO",
    "tpo anexo":                        "TPO_ANEXO",
    "num sic":                          "NUM_SIC",
    "numero sic":                       "NUM_SIC",
    "lei":                              "LEI",
    "id linea credito":                 "ID_LINEACREDITO",
    "id credito cnbv":                  "ID_CREDITO_CNBV",
    "identificador credito":            "ID_CREDITO_CNBV",
    "id linea grupal":                  "ID_LINEA_GRUPAL_CNBV",
    "destino":                          "DESTINO",
    "destino del credito":              "DESTINO",
    "monto linea valorizado":           "MONTO_LINEA_VALORIZADO",
    "monto valorizado":                 "MONTO_LINEA_VALORIZADO",
    "monto linea moneda origen":        "MONTO_LINEA_MONEDA_ORIGEN",
    "monto autorizado":                 "MONTO_LINEA_MONEDA_ORIGEN",
    "fecha otorgamiento":               "FECHA_OTORGAMIENTO",
    "fecha vencimiento":                "FECHA_VENCIMIENTO",
    "fecha maxima disposicion":         "FECHA_MAXIMA_DISP",
    "fecha maxima disp":                "FECHA_MAXIMA_DISP",
    "forma disposicion":                "FORMA_DISP",
    "forma disp":                       "FORMA_DISP",
    "revocable":                        "REVOCABLE",
    "prelacion":                        "PRELACION",
    "participaciones federales":        "PRC_PART_FEDERALES",
    "prc part federales":               "PRC_PART_FEDERALES",
    "clave institucion otorgante":      "CVE_INST_OTORGANTE",
    "cve inst otorgante":               "CVE_INST_OTORGANTE",
    "tipo alta":                        "TPO_ALTA",
    "tpo alta":                         "TPO_ALTA",
    "moneda":                           "MONEDA",
    "tipo tasa":                        "TPO_TASA",
    "tpo tasa":                         "TPO_TASA",
    "diferencial tasa":                 "DIF_TASA",
    "dif tasa":                         "DIF_TASA",
    "operador diferencial":             "OPER_DIF_TASA",
    "oper dif tasa":                    "OPER_DIF_TASA",
    "frecuencia revision tasa":         "FREC_REVISION_TASA",
    "frec revision tasa":               "FREC_REVISION_TASA",
    "periodicidad capital":             "PERIODICIDAD_CAPITAL",
    "periodicidad interes":             "PERIODICIDAD_INTERES",
    "meses gracia capital":             "MESES_GRACIA_CAPITAL",
    "meses gracia interes":             "MESES_GRACIA_INTERES",
    "comision apertura tasa":           "COMISION_APERTURA_TASA",
    "comision apertura monto":          "COMISION_APERTURA_MONTO",
    "comision disposicion tasa":        "COMISION_DISPOSICION_TASA",
    "comision disposicion monto":       "COMISION_DISPOSICION_MONTO",
    "cat":                              "CAT",
    "monto linea sin accesorios":       "MONTO_LINEA_SIN_ACCESORIOS",
    "monto primas anuales":             "MONTO_PRIMAS_ANUALES",
    "localidad destino":                "LOCALIDAD_DESTINO",
    "municipio destino":                "MUNICIPIO_DESTINO",
    "estado destino":                   "ESTADO_DESTINO",
    "actividad economica destino":      "ACT_ECONOMICA_DESTINO",
    "act economica destino":            "ACT_ECONOMICA_DESTINO",

    # Nombres largos del CUB (analisis_0430.json)
    "clave de la institucion":                                          "CLAVE_INSTITUCION",
    "identificador del acreditado asignado por la institucion":         "ID_ACREDITADO",
    "nombre del acreditado":                                            "NOMBRE",
    "rfc del acreditado":                                               "RFC",
    "curp del acreditado":                                              "CURP",
    "localidad del domicilio del acreditado":                           "LOCALIDAD",
    "municipio del domicilio del acreditado":                           "MUNICIPIO",
    "estado del domicilio del acreditado":                              "ESTADO",
    "nacionalidad del acreditado":                                      "NACIONALIDAD",
    "actividad economica del acreditado":                               "ACT_ECONOMICA",
    "grupo de riesgo comun":                                            "GPO_RIESGO",
    "numero de consulta realizada a la sociedad de informacion crediticia": "NUM_SIC",
    "clave lei legal entity identifier":                                "LEI",
    "identificador del credito asignado por la institucion":            "ID_LINEACREDITO",
    "identificador del credito asignado metodologia cnbv":              "ID_CREDITO_CNBV",
    "identificador credito linea grupal asignado metodologia cnbv":     "ID_LINEA_GRUPAL_CNBV",
    "monto de la linea de credito autorizado valorizado en pesos":      "MONTO_LINEA_VALORIZADO",
    "monto de la linea de credito autorizado en la moneda de origen":   "MONTO_LINEA_MONEDA_ORIGEN",
    "fecha de otorgamiento de la linea de credito":                     "FECHA_OTORGAMIENTO",
    "fecha de vencimiento de la linea de credito":                      "FECHA_VENCIMIENTO",
    "fecha maxima para disponer de los recursos":                       "FECHA_MAXIMA_DISP",
    "forma de la disposicion":                                          "FORMA_DISP",
    "linea de credito revocable o irrevocable":                         "REVOCABLE",
    "prelacion de pago credito preferente o subordinado":               "PRELACION",
    "porcentaje de participaciones federales comprometidas como fuente de pago del credito": "PRC_PART_FEDERALES",
    "clave de la institucion o agencia del exterior otorgante de los recursos": "CVE_INST_OTORGANTE",
    "tipo de alta del credito":                                         "TPO_ALTA",
    "moneda de la linea de credito":                                    "MONEDA",
    "tipo de tasa de interes de la linea de credito":                   "TPO_TASA",
    "diferencial sobre tasa de referencia de la linea de credito":      "DIF_TASA",
    "operacion de diferencial sobre tasa de referencia aditiva o factor de la linea de credito": "OPER_DIF_TASA",
    "frecuencia de revision de la tasa de la linea de credito":         "FREC_REVISION_TASA",
    "periodicidad pagos de capital":                                    "PERIODICIDAD_CAPITAL",
    "periodicidad pagos de intereses":                                  "PERIODICIDAD_INTERES",
    "numero de meses de gracia para amortizar capital":                 "MESES_GRACIA_CAPITAL",
    "numero de meses de gracia para pago de intereses":                 "MESES_GRACIA_INTERES",
    "comision de apertura del credito tasa":                            "COMISION_APERTURA_TASA",
    "comision de apertura del credito monto":                           "COMISION_APERTURA_MONTO",
    "comision por disposicion del credito tasa":                        "COMISION_DISPOSICION_TASA",
    "comision por disposicion del credito monto":                       "COMISION_DISPOSICION_MONTO",
    "costo anual total cat":                                            "CAT",
    "monto del credito simple o monto autorizado de la linea de credito sin incluir accesorios financieros": "MONTO_LINEA_SIN_ACCESORIOS",
    "monto de las primas anuales de todos los seguros obligatorios":    "MONTO_PRIMAS_ANUALES",
    "localidad en donde se destinara el credito":                       "LOCALIDAD_DESTINO",
    "municipio en donde se destinara el credito":                       "MUNICIPIO_DESTINO",
    "estado en donde se destinara el credito":                          "ESTADO_DESTINO",
    "actividad economica a la que se destinara el credito":             "ACT_ECONOMICA_DESTINO",
}



# Mapa número de campo → clave del diccionario LINAJE_0430
NUMERO_CAMPO_0430 = {
    1:  "PERIODO",
    2:  "CLAVE_INSTITUCION",
    3:  "REPORTE",
    4:  "ID_ACREDITADO",
    5:  "NOMBRE",
    6:  "RFC",
    7:  "CURP",
    8:  "LOCALIDAD",
    9:  "MUNICIPIO",
    10: "ESTADO",
    11: "NACIONALIDAD",
    12: "ACT_ECONOMICA",
    13: "GPO_RIESGO",
    14: "ACRED_RELACIONADO",
    15: "TPO_CARTERA",
    16: "TPO_ANEXO",
    17: "NUM_SIC",
    18: "LEI",
    19: "ID_LINEACREDITO",
    20: "ID_CREDITO_CNBV",
    21: "ID_LINEA_GRUPAL_CNBV",
    22: "DESTINO",
    23: "MONTO_LINEA_VALORIZADO",
    24: "MONTO_LINEA_MONEDA_ORIGEN",
    25: "FECHA_OTORGAMIENTO",
    26: "FECHA_VENCIMIENTO",
    27: "FECHA_MAXIMA_DISP",
    28: "FORMA_DISP",
    29: "REVOCABLE",
    30: "PRELACION",
    31: "PRC_PART_FEDERALES",
    32: "CVE_INST_OTORGANTE",
    33: "TPO_ALTA",
    34: "MONEDA",
    35: "TPO_TASA",
    36: "DIF_TASA",
    37: "OPER_DIF_TASA",
    38: "FREC_REVISION_TASA",
    39: "PERIODICIDAD_CAPITAL",
    40: "PERIODICIDAD_INTERES",
    41: "MESES_GRACIA_CAPITAL",
    42: "MESES_GRACIA_INTERES",
    43: "COMISION_APERTURA_TASA",
    44: "COMISION_APERTURA_MONTO",
    45: "COMISION_DISPOSICION_TASA",
    46: "COMISION_DISPOSICION_MONTO",
    47: "CAT",
    48: "MONTO_LINEA_SIN_ACCESORIOS",
    49: "MONTO_PRIMAS_ANUALES",
    50: "LOCALIDAD_DESTINO",
    51: "MUNICIPIO_DESTINO",
    52: "ESTADO_DESTINO",
    53: "ACT_ECONOMICA_DESTINO",
}

def normalizar(texto):
    """Normaliza texto para búsqueda: minúsculas, sin acentos, sin paréntesis"""
    import unicodedata
    texto = texto.lower().strip()
    texto = ''.join(c for c in unicodedata.normalize('NFD', texto)
                    if unicodedata.category(c) != 'Mn')
    texto = texto.replace('(', '').replace(')', '').replace('  ', ' ')
    return texto


def buscar_linaje(texto):
    """Busca el linaje de un campo dado un texto libre"""
    texto_norm = normalizar(texto)

    # Buscar por número de campo primero
    import re
    numeros = re.findall(r'\b(\d{1,2})\b', texto.strip())
    for n in numeros:
        num = int(n)
        if num in NUMERO_CAMPO_0430:
            campo = NUMERO_CAMPO_0430[num]
            return campo, LINAJE_0430.get(campo)

    # Buscar por alias (nombre largo o corto)
    for alias, campo in ALIAS_0430.items():
        if normalizar(alias) in texto_norm:
            return campo, LINAJE_0430.get(campo)

    # Buscar por clave exacta del diccionario
    for campo in LINAJE_0430:
        if campo.lower() in texto_norm:
            return campo, LINAJE_0430[campo]

    return None, None